apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: grav-init

resources:
  - job.yaml

images:
  - name: grav-init #TODO
    newName: gcr.io/flying-blue-mantis/grav-init
