kind: ConfigMap
apiVersion: v1
metadata:
  name: php-config
data:
  00-overrides.conf: |
    ; #TODO something should hit nfs

    [www]
    ; access logs from nginx only
    access.log = /dev/null

    ; enable status page for readyz etc
    pm.status_path = /status

    ; enable ping page for healthz
    ping.path = /ping
  healthz.sh: |
    #!/usr/bin/env sh
    set -eux -o pipefail

    # test mount is ok and something installed. use read for timeout
    head -n1 /var/www/html/index.php | read -t1 || exit 50

    # test php is up (/ping must be configured)
    SCRIPT_NAME=/ping \
    SCRIPT_FILENAME=/ping \
    REQUEST_METHOD=GET \
    cgi-fcgi -bind -connect localhost:9000 | grep -q pong || exit 51
