kind: ConfigMap
apiVersion: v1
metadata:
  name: php-config
data:
  00-overrides.conf: |
    ; #TODO something should hit nfs

    [www]
    ; access logs from nginx only
    access.log = /dev/null

    ; enable status page for readyz etc
    pm.status_path = /status

    ; enable ping page for healthz
    ping.path = /ping
