kind: ConfigMap
apiVersion: v1
metadata:
  name: php-config
data:
  00-overrides.conf: |
    ; #TODO something should hit nfs

    [www]
    ; access logs from nginx only
    access.log = /dev/null

    ; enable status page for readyz etc
    pm.status_path = /status

    ; enable ping page for healthz
    ping.path = /ping
  healthz.sh: |
    #!/usr/bin/env sh
    set -eu -o pipefail
    export SCRIPT_NAME=/ping \
    export REQUEST_METHOD=GET \
    NFS_FILE=/var/www/html/robots.txt
    if test -f $NFS_FILE -ne 0; then
      echo $NFS_FILE not found. NFS may be down or no content has been initialized.
      exit 50
    fi
    cgi-fcgi -bind -connect localhost:9000 || exit 51
