apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels: {}
spec:
  selector:
    matchLabels: {}
  replicas: 1
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - image: php-fpm
        name: php-fpm
        ports:
        - containerPort: 9000
          name: php
        resources:
          requests:
            memory: "100Mi"
            cpu: "20m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        volumeMounts:
        - name: php-config
          mountPath: /usr/local/etc/php-fpm.d/00-overrides.conf
          subPath: 00-overrides.conf
        - name: webroot-pv
          mountPath: /var/www/html
      volumes:
      - name: php-config
        configMap:
          name: php-config
          defaultMode: 0555 #required to mount healthcheck :(
      - name: webroot-pv
        persistentVolumeClaim:
          claimName: webroot-pvc
        # https://www.reddit.com/r/kubernetes/comments/8yvlib/nginx_phpfpm_on_kubernetes/e36ne33/
        #TODO prometheus sidecar
