apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels: {}
spec:
  selector:
    matchLabels: {}
  replicas: 1
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - image: php-fpm
        name: php-fpm
        ports:
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: webroot-pv
          mountPath: /app
      volumes:
      - name: webroot-pv
        persistentVolumeClaim:
          claimName: webroot-pvc
        #TODO probes
        # https://www.reddit.com/r/kubernetes/comments/8yvlib/nginx_phpfpm_on_kubernetes/e36ne33/
        #TODO prometheus sidecar
