apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  template:
    spec:
      containers:
        - name: php-fpm
          livenessProbe:
            exec:
              command:
              - /healthz.sh
            initialDelaySeconds: 10
            periodSeconds: 3
          volumeMounts:
          - name: php-config
            mountPath: /healthz.sh
            subPath: healthz.sh
