apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: php-fpm

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

images:
  - name: php-fpm
    newName: bitnami/php-fpm
    newTag: 7.3.4-prod
