apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: php-fpm

resources:
  - deployment.yaml
  - service.yaml

# Images modify the images:
images:
  - name: php #TODO
    newName: grav
    newTag: 1.15.11-alpine
