apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: php-fpm

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml

images:
  - name: php-fpm
    newName: gcr.io/flying-blue-mantis/php-fpm
