apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webroot-pvc
  labels:
    app: "php-fpm"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1G"
  storageClassName: "nfs"
