apiVersion: v1
kind: Service
metadata:
  name: php-fpm-svc
  labels:
    app: "php-fpm"
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: php
      port: 9000
      targetPort: php
  selector:
    app: "php-fpm"
