apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: "nginx"
spec:
  rules: {}
  tls: {}
