apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $(HOSTNAME)
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: http
  tls:
  - hosts:
    - $(HOSTNAME)
    secretName: nginx-tls
