apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: nginx

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: nginx-config
  files:
    - configs/nginx.conf

vars:
- fieldref:
    fieldPath: data.hostname
  name: HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: site-data

images:
- name: nginx
  newTag: 1.15.11-alpine
patchesStrategicMerge:
- healthcheck_patch.yaml
