apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: nginx

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml

vars:
  - name: HOSTNAME
    objref:
      kind: ConfigMap
      name: site-data
      apiVersion: v1
    fieldref:
      fieldpath: data.hostname

images:
  - name: nginx
    newTag: 1.15.11-alpine
