apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php-backend
spec:
  selector:
    matchLabels:
      app: php-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: php-backend
    spec:
      containers:
      - image: php
        name: php
        ports:
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: webroot-pv
          mountPath: /var/www/html
        - name: php-fpm-config
          mountPath: /usr/local/etc/php-fpm.d/www.conf
          subPath: www.conf
      volumes:
      - name: php-fpm-config
        configMap:
          name: php-fpm-config
      - name: webroot-pv
        persistentVolumeClaim:
          claimName: webroot-pvc
        #TODO probes
        # https://www.reddit.com/r/kubernetes/comments/8yvlib/nginx_phpfpm_on_kubernetes/e36ne33/
        #TODO prometheus sidecar
